<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaventas [
    <!ELEMENT listaventas (venta+)>
    <!ELEMENT venta (importe, comprador, vendedor, fecha?, codigofactura)>
    <!ELEMENT importe (#PCDATA)>
    <!ELEMENT comprador (#PCDATA)>
    <!ELEMENT vendedor (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT codigofactura (#PCDATA)>
]>

<listaventas>
    <venta>
        <importe>100</importe>
        <comprador>Paco</comprador>
        <vendedor>Wanwe</vendedor>
        <fecha>11-03-2022</fecha>
        <codigofactura>01</codigofactura>
    </venta>
    <venta>
        <importe>150</importe>
        <comprador>Adrian</comprador>
        <vendedor>Noelia</vendedor>
        <codigofactura>02</codigofactura>
    </venta>
</listaventas>