<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacursos [
    <!ELEMENT listacursos (curso+)>
    <!ELEMENT curso (alumno+)>
    <!ELEMENT alumno (dni, nombre, apellido, segundoapellido?, asignatura+)>
    <!ELEMENT asignatura (nombre, profesor)>
        <!ATTLIST asignatura codigo ID #REQUIRED>
    <!ELEMENT profesor (nrp, nombre, apellido, segundoapellido?)>
    <!ELEMENT dni (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT segundoapellido (#PCDATA)>
    <!ELEMENT nrp (#PCDATA)>
]>

<listacursos>
    <curso>
        <alumno>
            <dni>12414412B</dni>
            <nombre>Ángel</nombre>
            <apellido>García</apellido>
            <asignatura codigo="LDM">
                <nombre>Lenguaje De Marcas</nombre>
                <profesor>
                    <nrp>0121</nrp>
                    <nombre>...</nombre>
                    <apellido>...</apellido>
                    <segundoapellido>...</segundoapellido>
                </profesor>
            </asignatura>
        </alumno>
    </curso>
</listacursos>